version: 2
jobs:
    build_deploy:
        docker:
            - image: circleci/node:10.4-browsers

        working_directory: ~/repo

        steps:
            - checkout

        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-

        - run: 
            name: Install Dependancies
            command: yarn

        - save_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
            paths: node_modules

        - run: 
            name: Build
            command: yarn build

        - run:
            name: Deploy
            command: yarn firebase deploy --token "${FIREBASE_TOKEN} --only hosting"

    deploy:
        docker:
            - image: circleci/node:10.4-browsers

        working_directory: ~/repo/functions

        stesp:
            - checkout
        
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
        
        - run: 
            name: Install Dependancies
            command: yarn

        - save_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
            paths: node_modules
        
        - run:
            name: Deploy
            command: yarn firebase deploy --token "${FIREBASE_TOKEN}" --only functions

workflows:
    version: 2
    build_and_deply:
        jobs:
            - build_deploy
            - deploy_functions
